### ISSUE TITLE
Error on Evaluation

### ISSUE THREAD

**Issue by mahfujau** [harshitbansal05/Deep-Coral-Tf#1]
Hi,

I just run your code and found the following errors.

```
 File "eval_net.py", line 84, in evaluate
    model = AlexNet(images, keep_prob, NUM_CLASSES, train_layers, 'source/')
NameError: name 'AlexNet' is not defined
```

Can you please fix the proplem?

**Comment by harshitbansal05** [comment]
Sorry, I could'nt check it as my computer was running out of ram. It was missing an import statement and has been fixed in this [https://github.com/harshitbansal05/Deep-Coral-Tf/commit/13d62512760ecd2b164685567d2afc49f41b1fe6](https://github.com/harshitbansal05/Deep-Coral-Tf/commit/13d62512760ecd2b164685567d2afc49f41b1fe6). 
Kindly re-open it if any other issue arises.
Thanks.
